# Generated by Django 4.1.1 on 2022-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_music_app', '0002_artist_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='surname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
