# Generated by Django 4.1.1 on 2022-10-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guestTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_set', to='football_app.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hostTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='football_app.team'),
        ),
    ]
