# Generated by Django 4.1.1 on 2022-10-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0004_gamedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, to='games_app.category'),
        ),
    ]
