# Generated by Django 4.1.1 on 2022-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0005_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='play_time',
            field=models.DurationField(),
        ),
    ]
