# Generated by Django 4.1.1 on 2022-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0006_alter_gamedetails_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='cheat_codes',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
