# Generated by Django 4.1.1 on 2022-10-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0007_alter_gamedetails_cheat_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='url',
        ),
    ]
