# Generated by Django 4.1.1 on 2022-10-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostScore', models.IntegerField()),
                ('guestScore', models.IntegerField()),
                ('guestTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestSet', to='footbal_app.team')),
                ('hostTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostSet', to='footbal_app.team')),
            ],
        ),
    ]
